In [23]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [11]:
data = pd.read_csv('data.csv')
data

      Name  Gender       City Passed  Age  Salary
0     Aman    Male      Delhi    Yes   22   50000
1    Priya  Female     Mumbai    Yes   24   62000
2    Rahul    Male  Bangalore     No   21   40000
3   Anjali  Female     Mumbai    Yes   23   58000
4     Ravi    Male      Delhi    Yes   25   65000
5    Meera  Female    Chennai     No   20   35000
6    Arjun    Male  Bangalore    Yes   26   70000
7     Neha  Female      Delhi    Yes   23   55000
8    Imran    Male    Chennai     No   22   42000
9    Sneha  Female     Mumbai    Yes   24   60000
10     Raj    Male    Chennai    Yes   27   72000
11   Divya  Female      Delhi     No   21   38000
12   Kabir    Male     Mumbai    Yes   25   64000
13  Simran  Female  Bangalore    Yes   23   59000
14   Karan    Male      Delhi     No   22   39000
15   Pooja  Female     Mumbai    Yes   24   61000
16  Rakesh    Male    Chennai    Yes   28   75000
17    Isha  Female      Delhi     No   21   37000
18   Rohit    Male      Delhi    Yes   25   66000
19   Deepa  Female  Bangalore    Yes   24   63000

In [21]:
stscale = StandardScaler()
data[['Scaled_Age']]=stscale.fit_transform(data[['Age']])

In [28]:
mmscale = MinMaxScaler(feature_range = (0,1))
data[['Scaled_Salary']] = mmscale.fit_transform(data[['Salary']])

In [29]:
data

      Name  Gender       City Passed  Age  Salary  Scaled_Age  Scaled_Salary
0     Aman    Male      Delhi    Yes   22   50000   -0.727607          0.375
1    Priya  Female     Mumbai    Yes   24   62000    0.242536          0.675
2    Rahul    Male  Bangalore     No   21   40000   -1.212678          0.125
3   Anjali  Female     Mumbai    Yes   23   58000   -0.242536          0.575
4     Ravi    Male      Delhi    Yes   25   65000    0.727607          0.750
5    Meera  Female    Chennai     No   20   35000   -1.697749          0.000
6    Arjun    Male  Bangalore    Yes   26   70000    1.212678          0.875
7     Neha  Female      Delhi    Yes   23   55000   -0.242536          0.500
8    Imran    Male    Chennai     No   22   42000   -0.727607          0.175
9    Sneha  Female     Mumbai    Yes   24   60000    0.242536          0.625
10     Raj    Male    Chennai    Yes   27   72000    1.697749          0.925
11   Divya  Female      Delhi     No   21   38000   -1.212678          0.075
12   Kabir    Male     Mumbai    Yes   25   64000    0.727607          0.725
13  Simran  Female  Bangalore    Yes   23   59000   -0.242536          0.600
14   Karan    Male      Delhi     No   22   39000   -0.727607          0.100
15   Pooja  Female     Mumbai    Yes   24   61000    0.242536          0.650
16  Rakesh    Male    Chennai    Yes   28   75000    2.182821          1.000
17    Isha  Female      Delhi     No   21   37000   -1.212678          0.050
18   Rohit    Male      Delhi    Yes   25   66000    0.727607          0.775
19   Deepa  Female  Bangalore    Yes   24   63000    0.242536          0.700